# ----------------------- #
#      Main Configs       #
# ----------------------- #

title: Robostox
author: Daniel Easterman
description: Tools and weekly reports on tech stocks and crypto for the 21st century investor.
copyright: ""

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
# Causing css and js to fail:
# permalink: pretty
# Don't need this as simpler without _pages folder
# include: ["_pages"]
